modLoader="javafml"
loaderVersion="[4,)"
license="GNU GPLv3"

[[mods]]
modId="wscommands"
version="1.0.7"
displayName="World Start Commands and Global Configs"
displayURL="https://modrinth.com/user/acewins"
credits=""
authors="acewins"
description="Runs commands on world creation!"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.wscommands]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wscommands]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration