modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"

[[mods]]
modId="wscommands"
version="1.0.2"
displayName="World Start Commands and Global Gamerules"
displayURL="https://github.com/acewins727/WSCommands"
authors="acewins"
description="Runs commands on world creation!"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.wscommands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"
