modLoader="javafml"
loaderVersion="[2,)"
license="GNU GPLv3"

[[mods]]
modId="wscommands"
version="1.0.2"
displayName="World Start Commands and Global Gamerules"
displayURL="https://github.com/acewins727/WSCommands"
authors="acewins"
description="Runs commands on world creation!"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.wscommands]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.wscommands]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"
